### ISSUE TITLE
StaticModelGroup

### ISSUE THREAD

**Issue by t-artikov** [MonkeyFirst/sceneTestFrom122#1]
Сейчас по-прежнему упирается в процессор(отсечение геометрии, расчет источников света), чтобы исправить ситуацию попробуй использовать StaticModelGroup(как в примере 20_HugeObjectCount).

**Comment by MonkeyFirst** [comment]
Так там и так 15-ть батчей всего, что соответствует примерному кол-ву материалов в сцене.
Я что-то сомневаюсь что SMG как-то кардинально изменит ситуацию.

**Comment by t-artikov** [comment]
Должно изменить, отсечение станет работать быстрее.
Есть правда шанс, что из-за того, что будут рисоваться объекты, которые реально не видны, возрастет нагрузка на GPU и все станет только хуже).

**Comment by MonkeyFirst** [comment]
Да ты прав оказался, в среднем с ~1000fps возросло до ~1633 fps'a на моей 970й в фулашди
